version: 0.1

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'output'
  name: output.zip

cache:
  paths:
    - '/root/.npm/**/*'