version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      - echo Running tests...
      - echo Tests started on `date`
      - npm run test-ci
  post_build:
    commands:
      - echo Tests completed on `date`

cache:
  paths:
    - '/root/.npm/**/*'